# Generated by Django 3.2.20 on 2026-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0006_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PMS', 'PMS'), ('AGO', 'AGO'), ('HYBRID', 'Hybrid'), ('EV', 'Electric')], default='PMS', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10),
        ),
    ]
