# Generated by Django 3.2.20 on 2026-02-17 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0007_auto_20260217_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPriceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('PMS', 'PMS'), ('AGO', 'AGO'), ('HYBRID', 'Hybrid'), ('EV', 'Electric')], max_length=10, unique=True)),
                ('price_per_litre_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_litre', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='inspection_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='replacement_schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='TyreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('life_span_km', models.FloatField(blank=True, null=True)),
                ('replacement_due_date', models.DateField(blank=True, null=True)),
                ('inspection_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_records', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('incident_type', models.CharField(default='Defect', max_length=64)),
                ('details', models.TextField()),
                ('status', models.CharField(default='Open', max_length=32)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DriverStyleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('acceleration_events', models.PositiveIntegerField(default=0)),
                ('deceleration_events', models.PositiveIntegerField(default=0)),
                ('harsh_braking_events', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_style_records', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_style_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=128)),
                ('end_point', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('gps_distance_km', models.FloatField(blank=True, null=True)),
                ('start_odometer_km', models.FloatField(blank=True, null=True)),
                ('end_odometer_km', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_records', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('before_driving_notes', models.TextField(blank=True, null=True)),
                ('after_driving_notes', models.TextField(blank=True, null=True)),
                ('odometer_before_km', models.FloatField(blank=True, null=True)),
                ('odometer_after_km', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checklists', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BatteryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('life_span_days', models.PositiveIntegerField(blank=True, null=True)),
                ('replacement_due_date', models.DateField(blank=True, null=True)),
                ('inspection_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_records', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
