# Generated by Django 3.2.20 on 2026-02-17 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autodo', '0008_auto_20260217_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_service_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='servicing_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='brake_fluid_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='coolant_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='engine_oil_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='tyre_pressure_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='water_level_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='actual_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='actual_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='downtime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='downtime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='estimated_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='estimated_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('OWNER_MANAGER', 'Owner/Manager'), ('TRANSPORT_OFFICER', 'Motor Transport Officer')], default='DRIVER', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('MAINTENANCE', 'Maintenance'), ('DOWN', 'Down'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, max_length=128, null=True)),
                ('mileage_km', models.FloatField(blank=True, null=True)),
                ('total_cost_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('total_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='CriticalPartInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('part', models.CharField(choices=[('BRAKES', 'Brakes'), ('ENGINE', 'Engine'), ('TRANSMISSION', 'Transmission'), ('TYRES', 'Tyres'), ('BATTERY', 'Battery'), ('COOLING', 'Cooling System'), ('SUSPENSION', 'Suspension')], max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('ATTENTION', 'Needs Attention'), ('CRITICAL', 'Critical')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_repair_cost_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('estimated_repair_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_part_checks', to='autodo.car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_part_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
